extract RHEL VERSION string from the RHEL kernel version
Signed-off-by: Tariq Ibrahim <tibrahim@nvidia.com>

diff --git a/rhel8/precompiled/nvidia-driver b/rhel8/precompiled/nvidia-driver
--- a/rhel8/precompiled/nvidia-driver
+++ b/rhel8/precompiled/nvidia-driver
@@ -14,6 +14,8 @@ NVIDIA_MODESET_MODULE_PARAMS=()
 NVIDIA_PEERMEM_MODULE_PARAMS=()
 TARGETARCH=${TARGETARCH:?"Missing TARGETARCH env"}
 USE_HOST_MOFED="${USE_HOST_MOFED:-false}"
+DNF_RELEASEVER=${DNF_RELEASEVER:-""}
+RHEL_VERSION=${RHEL_VERSION:-""}
 
 DRIVER_ARCH=${TARGETARCH/amd64/x86_64} && DRIVER_ARCH=${DRIVER_ARCH/arm64/aarch64}
 echo "DRIVER_ARCH is $DRIVER_ARCH"
@@ -39,22 +41,40 @@ _cleanup_package_cache() {
     fi
 }
 
+_get_rhel_version_from_kernel() {
+    local rhel_version_underscore rhel_version_arr
+    rhel_version_underscore=$(uname -r | sed 's/.*el\([0-9]_[0-9]\).*/\1/g')
+    if [[ ${#rhel_version_underscore} -ne 3 ]]; then
+        echo "Unable to resolve RHEL version from kernel version" >&2
+        return 1
+    fi
+    IFS='_' read -r -a rhel_version_arr <<< "$rhel_version_underscore"
+    RHEL_VERSION="${rhel_version_arr[0]}.${rhel_version_arr[1]}"
+    return 0
+}
+
+_get_rhel_version_from_etc_os_release() {
+    local version=""
+    local id=$(cat /host-etc/os-release | grep ^ID= | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
+    if [ "${id}" = "rhcos" ]; then
+        version=$(cat /host-etc/os-release | grep RHEL_VERSION | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
+    elif [ "${id}" = "rhel" ]; then
+        version=$(cat /host-etc/os-release | grep VERSION_ID | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
+    fi
+    if [ -z "${version}" ]; then
+        echo "Could not resolve RHEL version" >&2
+        return 1
+    fi
+    RHEL_VERSION="${version}"
+    echo "Proceeding with RHEL version ${RHEL_VERSION}"
+    return 0
+}
+
 _resolve_rhel_version() {
-    if [ -f /host-etc/os-release ]; then
-        echo "Resolving RHEL version..."
-        local version=""
-        local id=$(cat /host-etc/os-release | grep ^ID= | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
-        if [ "${id}" = "rhcos" ]; then
-            version=$(cat /host-etc/os-release | grep RHEL_VERSION | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
-        elif [ "${id}" = "rhel" ]; then
-            version=$(cat /host-etc/os-release | grep VERSION_ID | awk -F= '{print $2}' | sed -e 's/^"//' -e 's/"$//')
-        fi
-        if [ -z "${version}" ]; then
-            echo "Could not resolve RHEL version" >&2
-            return 1
-        fi
-        RHEL_VERSION="${version}"
-        echo "Proceeding with RHEL version ${RHEL_VERSION}"
+    _get_rhel_version_from_kernel || _get_rhel_version_from_etc_os_release
+    # set dnf release version as rhel version by default
+    if [[ -z "${DNF_RELEASEVER}" ]]; then
+        DNF_RELEASEVER="${RHEL_VERSION}"
     fi
     return 0
 }
@@ -413,7 +433,7 @@ reload_nvidia_peermem() {
     exit 1
 }
 
-# probe by gpu-opertor for liveness/startup checks for nvidia-peermem module to be loaded when MOFED drivers are ready
+# probe by gpu-operator for liveness/startup checks for nvidia-peermem module to be loaded when MOFED drivers are ready
 probe_nvidia_peermem() {
     if lsmod | grep mlx5_core > /dev/null 2>&1; then
         if [ ! -f /sys/module/nvidia_peermem/refcnt ]; then
